#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDH")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKenhTinBaiViet(KenhTinBaiViet instance);
    partial void UpdateKenhTinBaiViet(KenhTinBaiViet instance);
    partial void DeleteKenhTinBaiViet(KenhTinBaiViet instance);
    partial void InsertTinBaiViet(TinBaiViet instance);
    partial void UpdateTinBaiViet(TinBaiViet instance);
    partial void DeleteTinBaiViet(TinBaiViet instance);
    partial void InsertLichSuDonHang(LichSuDonHang instance);
    partial void UpdateLichSuDonHang(LichSuDonHang instance);
    partial void DeleteLichSuDonHang(LichSuDonHang instance);
    partial void InsertQuanLyDonHang(QuanLyDonHang instance);
    partial void UpdateQuanLyDonHang(QuanLyDonHang instance);
    partial void DeleteQuanLyDonHang(QuanLyDonHang instance);
    partial void InsertQuanLyKhoHang(QuanLyKhoHang instance);
    partial void UpdateQuanLyKhoHang(QuanLyKhoHang instance);
    partial void DeleteQuanLyKhoHang(QuanLyKhoHang instance);
    partial void InsertQuanLyLoHang(QuanLyLoHang instance);
    partial void UpdateQuanLyLoHang(QuanLyLoHang instance);
    partial void DeleteQuanLyLoHang(QuanLyLoHang instance);
    partial void InsertQuanLyTaiKhoan(QuanLyTaiKhoan instance);
    partial void UpdateQuanLyTaiKhoan(QuanLyTaiKhoan instance);
    partial void DeleteQuanLyTaiKhoan(QuanLyTaiKhoan instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDHConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KenhTinBaiViet> KenhTinBaiViets
		{
			get
			{
				return this.GetTable<KenhTinBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<TinBaiViet> TinBaiViets
		{
			get
			{
				return this.GetTable<TinBaiViet>();
			}
		}
		
		public System.Data.Linq.Table<LichSuDonHang> LichSuDonHangs
		{
			get
			{
				return this.GetTable<LichSuDonHang>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyDonHang> QuanLyDonHangs
		{
			get
			{
				return this.GetTable<QuanLyDonHang>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyKhoHang> QuanLyKhoHangs
		{
			get
			{
				return this.GetTable<QuanLyKhoHang>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyLoHang> QuanLyLoHangs
		{
			get
			{
				return this.GetTable<QuanLyLoHang>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyTaiKhoan> QuanLyTaiKhoans
		{
			get
			{
				return this.GetTable<QuanLyTaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KenhTinBaiViet")]
	public partial class KenhTinBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NoiDung;
		
		private System.Nullable<int> _MaCapTren;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnMaCapTrenChanging(System.Nullable<int> value);
    partial void OnMaCapTrenChanged();
    #endregion
		
		public KenhTinBaiViet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCapTren", DbType="Int")]
		public System.Nullable<int> MaCapTren
		{
			get
			{
				return this._MaCapTren;
			}
			set
			{
				if ((this._MaCapTren != value))
				{
					this.OnMaCapTrenChanging(value);
					this.SendPropertyChanging();
					this._MaCapTren = value;
					this.SendPropertyChanged("MaCapTren");
					this.OnMaCapTrenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinBaiViet")]
	public partial class TinBaiViet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TieuDe;
		
		private string _TomTat;
		
		private string _NoiDung;
		
		private string _TacGia;
		
		private System.Nullable<int> _IdKenhTin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnTomTatChanging(string value);
    partial void OnTomTatChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnIdKenhTinChanging(System.Nullable<int> value);
    partial void OnIdKenhTinChanged();
    #endregion
		
		public TinBaiViet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(100)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTat", DbType="NVarChar(800)")]
		public string TomTat
		{
			get
			{
				return this._TomTat;
			}
			set
			{
				if ((this._TomTat != value))
				{
					this.OnTomTatChanging(value);
					this.SendPropertyChanging();
					this._TomTat = value;
					this.SendPropertyChanged("TomTat");
					this.OnTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(100)")]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKenhTin", DbType="Int")]
		public System.Nullable<int> IdKenhTin
		{
			get
			{
				return this._IdKenhTin;
			}
			set
			{
				if ((this._IdKenhTin != value))
				{
					this.OnIdKenhTinChanging(value);
					this.SendPropertyChanging();
					this._IdKenhTin = value;
					this.SendPropertyChanged("IdKenhTin");
					this.OnIdKenhTinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuDonHang")]
	public partial class LichSuDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdDonHang;
		
		private System.Nullable<int> _TaiKhoanKhach;
		
		private System.Nullable<int> _KhoHangGui;
		
		private string _NguoiGui;
		
		private System.Nullable<int> _KhoHangNhan;
		
		private string _NguoiNhan;
		
		private System.Nullable<int> _TrangThai;
		
		private System.Nullable<System.DateTime> _ThoiDiemXuLy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdDonHangChanging(System.Nullable<int> value);
    partial void OnIdDonHangChanged();
    partial void OnTaiKhoanKhachChanging(System.Nullable<int> value);
    partial void OnTaiKhoanKhachChanged();
    partial void OnKhoHangGuiChanging(System.Nullable<int> value);
    partial void OnKhoHangGuiChanged();
    partial void OnNguoiGuiChanging(string value);
    partial void OnNguoiGuiChanged();
    partial void OnKhoHangNhanChanging(System.Nullable<int> value);
    partial void OnKhoHangNhanChanged();
    partial void OnNguoiNhanChanging(string value);
    partial void OnNguoiNhanChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnThoiDiemXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiDiemXuLyChanged();
    #endregion
		
		public LichSuDonHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDonHang", DbType="Int")]
		public System.Nullable<int> IdDonHang
		{
			get
			{
				return this._IdDonHang;
			}
			set
			{
				if ((this._IdDonHang != value))
				{
					this.OnIdDonHangChanging(value);
					this.SendPropertyChanging();
					this._IdDonHang = value;
					this.SendPropertyChanged("IdDonHang");
					this.OnIdDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanKhach", DbType="Int")]
		public System.Nullable<int> TaiKhoanKhach
		{
			get
			{
				return this._TaiKhoanKhach;
			}
			set
			{
				if ((this._TaiKhoanKhach != value))
				{
					this.OnTaiKhoanKhachChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanKhach = value;
					this.SendPropertyChanged("TaiKhoanKhach");
					this.OnTaiKhoanKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoHangGui", DbType="Int")]
		public System.Nullable<int> KhoHangGui
		{
			get
			{
				return this._KhoHangGui;
			}
			set
			{
				if ((this._KhoHangGui != value))
				{
					this.OnKhoHangGuiChanging(value);
					this.SendPropertyChanging();
					this._KhoHangGui = value;
					this.SendPropertyChanged("KhoHangGui");
					this.OnKhoHangGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiGui", DbType="NVarChar(100)")]
		public string NguoiGui
		{
			get
			{
				return this._NguoiGui;
			}
			set
			{
				if ((this._NguoiGui != value))
				{
					this.OnNguoiGuiChanging(value);
					this.SendPropertyChanging();
					this._NguoiGui = value;
					this.SendPropertyChanged("NguoiGui");
					this.OnNguoiGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoHangNhan", DbType="Int")]
		public System.Nullable<int> KhoHangNhan
		{
			get
			{
				return this._KhoHangNhan;
			}
			set
			{
				if ((this._KhoHangNhan != value))
				{
					this.OnKhoHangNhanChanging(value);
					this.SendPropertyChanging();
					this._KhoHangNhan = value;
					this.SendPropertyChanged("KhoHangNhan");
					this.OnKhoHangNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhan", DbType="NVarChar(100)")]
		public string NguoiNhan
		{
			get
			{
				return this._NguoiNhan;
			}
			set
			{
				if ((this._NguoiNhan != value))
				{
					this.OnNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhan = value;
					this.SendPropertyChanged("NguoiNhan");
					this.OnNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiDiemXuLy
		{
			get
			{
				return this._ThoiDiemXuLy;
			}
			set
			{
				if ((this._ThoiDiemXuLy != value))
				{
					this.OnThoiDiemXuLyChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiemXuLy = value;
					this.SendPropertyChanged("ThoiDiemXuLy");
					this.OnThoiDiemXuLyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyDonHang")]
	public partial class QuanLyDonHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TaiKhoanDatHang;
		
		private string _TaiKhoanKhach;
		
		private string _TenHang;
		
		private string _TenKhach;
		
		private string _LinkSP;
		
		private System.Nullable<int> _GiaSP;
		
		private System.Nullable<int> _DatCoc;
		
		private System.Nullable<int> _GiaSPCanThu;
		
		private System.Nullable<double> _CanNang;
		
		private System.Nullable<double> _TheTich;
		
		private System.Nullable<int> _CuocVanChuyen;
		
		private string _HangVanChuyen;
		
		private string _MaVanChuyen;
		
		private System.Nullable<int> _TrangThaiDonHang;
		
		private string _KhoHangNhan;
		
		private string _ChuyenPhat;
		
		private string _NguoiNhanCuoi;
		
		private string _KhoHangCuoi;
		
		private string _OrderNumber;
		
		private System.Nullable<System.DateTime> _NgayDatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTaiKhoanDatHangChanging(string value);
    partial void OnTaiKhoanDatHangChanged();
    partial void OnTaiKhoanKhachChanging(string value);
    partial void OnTaiKhoanKhachChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnTenKhachChanging(string value);
    partial void OnTenKhachChanged();
    partial void OnLinkSPChanging(string value);
    partial void OnLinkSPChanged();
    partial void OnGiaSPChanging(System.Nullable<int> value);
    partial void OnGiaSPChanged();
    partial void OnDatCocChanging(System.Nullable<int> value);
    partial void OnDatCocChanged();
    partial void OnGiaSPCanThuChanging(System.Nullable<int> value);
    partial void OnGiaSPCanThuChanged();
    partial void OnCanNangChanging(System.Nullable<double> value);
    partial void OnCanNangChanged();
    partial void OnTheTichChanging(System.Nullable<double> value);
    partial void OnTheTichChanged();
    partial void OnCuocVanChuyenChanging(System.Nullable<int> value);
    partial void OnCuocVanChuyenChanged();
    partial void OnHangVanChuyenChanging(string value);
    partial void OnHangVanChuyenChanged();
    partial void OnMaVanChuyenChanging(string value);
    partial void OnMaVanChuyenChanged();
    partial void OnTrangThaiDonHangChanging(System.Nullable<int> value);
    partial void OnTrangThaiDonHangChanged();
    partial void OnKhoHangNhanChanging(string value);
    partial void OnKhoHangNhanChanged();
    partial void OnChuyenPhatChanging(string value);
    partial void OnChuyenPhatChanged();
    partial void OnNguoiNhanCuoiChanging(string value);
    partial void OnNguoiNhanCuoiChanged();
    partial void OnKhoHangCuoiChanging(string value);
    partial void OnKhoHangCuoiChanged();
    partial void OnOrderNumberChanging(string value);
    partial void OnOrderNumberChanged();
    partial void OnNgayDatHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatHangChanged();
    #endregion
		
		public QuanLyDonHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanDatHang", DbType="NVarChar(100)")]
		public string TaiKhoanDatHang
		{
			get
			{
				return this._TaiKhoanDatHang;
			}
			set
			{
				if ((this._TaiKhoanDatHang != value))
				{
					this.OnTaiKhoanDatHangChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanDatHang = value;
					this.SendPropertyChanged("TaiKhoanDatHang");
					this.OnTaiKhoanDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanKhach", DbType="NVarChar(100)")]
		public string TaiKhoanKhach
		{
			get
			{
				return this._TaiKhoanKhach;
			}
			set
			{
				if ((this._TaiKhoanKhach != value))
				{
					this.OnTaiKhoanKhachChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanKhach = value;
					this.SendPropertyChanged("TaiKhoanKhach");
					this.OnTaiKhoanKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(500)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhach", DbType="NVarChar(100)")]
		public string TenKhach
		{
			get
			{
				return this._TenKhach;
			}
			set
			{
				if ((this._TenKhach != value))
				{
					this.OnTenKhachChanging(value);
					this.SendPropertyChanging();
					this._TenKhach = value;
					this.SendPropertyChanged("TenKhach");
					this.OnTenKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkSP", DbType="NVarChar(100)")]
		public string LinkSP
		{
			get
			{
				return this._LinkSP;
			}
			set
			{
				if ((this._LinkSP != value))
				{
					this.OnLinkSPChanging(value);
					this.SendPropertyChanging();
					this._LinkSP = value;
					this.SendPropertyChanged("LinkSP");
					this.OnLinkSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSP", DbType="Int")]
		public System.Nullable<int> GiaSP
		{
			get
			{
				return this._GiaSP;
			}
			set
			{
				if ((this._GiaSP != value))
				{
					this.OnGiaSPChanging(value);
					this.SendPropertyChanging();
					this._GiaSP = value;
					this.SendPropertyChanged("GiaSP");
					this.OnGiaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatCoc", DbType="Int")]
		public System.Nullable<int> DatCoc
		{
			get
			{
				return this._DatCoc;
			}
			set
			{
				if ((this._DatCoc != value))
				{
					this.OnDatCocChanging(value);
					this.SendPropertyChanging();
					this._DatCoc = value;
					this.SendPropertyChanged("DatCoc");
					this.OnDatCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSPCanThu", DbType="Int")]
		public System.Nullable<int> GiaSPCanThu
		{
			get
			{
				return this._GiaSPCanThu;
			}
			set
			{
				if ((this._GiaSPCanThu != value))
				{
					this.OnGiaSPCanThuChanging(value);
					this.SendPropertyChanging();
					this._GiaSPCanThu = value;
					this.SendPropertyChanged("GiaSPCanThu");
					this.OnGiaSPCanThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanNang", DbType="Float")]
		public System.Nullable<double> CanNang
		{
			get
			{
				return this._CanNang;
			}
			set
			{
				if ((this._CanNang != value))
				{
					this.OnCanNangChanging(value);
					this.SendPropertyChanging();
					this._CanNang = value;
					this.SendPropertyChanged("CanNang");
					this.OnCanNangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheTich", DbType="Float")]
		public System.Nullable<double> TheTich
		{
			get
			{
				return this._TheTich;
			}
			set
			{
				if ((this._TheTich != value))
				{
					this.OnTheTichChanging(value);
					this.SendPropertyChanging();
					this._TheTich = value;
					this.SendPropertyChanged("TheTich");
					this.OnTheTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocVanChuyen", DbType="Int")]
		public System.Nullable<int> CuocVanChuyen
		{
			get
			{
				return this._CuocVanChuyen;
			}
			set
			{
				if ((this._CuocVanChuyen != value))
				{
					this.OnCuocVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._CuocVanChuyen = value;
					this.SendPropertyChanged("CuocVanChuyen");
					this.OnCuocVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HangVanChuyen", DbType="NVarChar(100)")]
		public string HangVanChuyen
		{
			get
			{
				return this._HangVanChuyen;
			}
			set
			{
				if ((this._HangVanChuyen != value))
				{
					this.OnHangVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._HangVanChuyen = value;
					this.SendPropertyChanged("HangVanChuyen");
					this.OnHangVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanChuyen", DbType="NVarChar(100)")]
		public string MaVanChuyen
		{
			get
			{
				return this._MaVanChuyen;
			}
			set
			{
				if ((this._MaVanChuyen != value))
				{
					this.OnMaVanChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaVanChuyen = value;
					this.SendPropertyChanged("MaVanChuyen");
					this.OnMaVanChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDonHang", DbType="Int")]
		public System.Nullable<int> TrangThaiDonHang
		{
			get
			{
				return this._TrangThaiDonHang;
			}
			set
			{
				if ((this._TrangThaiDonHang != value))
				{
					this.OnTrangThaiDonHangChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiDonHang = value;
					this.SendPropertyChanged("TrangThaiDonHang");
					this.OnTrangThaiDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoHangNhan", DbType="NVarChar(100)")]
		public string KhoHangNhan
		{
			get
			{
				return this._KhoHangNhan;
			}
			set
			{
				if ((this._KhoHangNhan != value))
				{
					this.OnKhoHangNhanChanging(value);
					this.SendPropertyChanging();
					this._KhoHangNhan = value;
					this.SendPropertyChanged("KhoHangNhan");
					this.OnKhoHangNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenPhat", DbType="NVarChar(200)")]
		public string ChuyenPhat
		{
			get
			{
				return this._ChuyenPhat;
			}
			set
			{
				if ((this._ChuyenPhat != value))
				{
					this.OnChuyenPhatChanging(value);
					this.SendPropertyChanging();
					this._ChuyenPhat = value;
					this.SendPropertyChanged("ChuyenPhat");
					this.OnChuyenPhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhanCuoi", DbType="NVarChar(200)")]
		public string NguoiNhanCuoi
		{
			get
			{
				return this._NguoiNhanCuoi;
			}
			set
			{
				if ((this._NguoiNhanCuoi != value))
				{
					this.OnNguoiNhanCuoiChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhanCuoi = value;
					this.SendPropertyChanged("NguoiNhanCuoi");
					this.OnNguoiNhanCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoHangCuoi", DbType="NVarChar(200)")]
		public string KhoHangCuoi
		{
			get
			{
				return this._KhoHangCuoi;
			}
			set
			{
				if ((this._KhoHangCuoi != value))
				{
					this.OnKhoHangCuoiChanging(value);
					this.SendPropertyChanging();
					this._KhoHangCuoi = value;
					this.SendPropertyChanged("KhoHangCuoi");
					this.OnKhoHangCuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", DbType="NVarChar(100)")]
		public string OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDatHang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDatHang
		{
			get
			{
				return this._NgayDatHang;
			}
			set
			{
				if ((this._NgayDatHang != value))
				{
					this.OnNgayDatHangChanging(value);
					this.SendPropertyChanging();
					this._NgayDatHang = value;
					this.SendPropertyChanged("NgayDatHang");
					this.OnNgayDatHangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyKhoHang")]
	public partial class QuanLyKhoHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DiaChiKhoHang;
		
		private string _TenKho;
		
		private System.Nullable<int> _CapKho;
		
		private System.Nullable<int> _TinhTrang;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDiaChiKhoHangChanging(string value);
    partial void OnDiaChiKhoHangChanged();
    partial void OnTenKhoChanging(string value);
    partial void OnTenKhoChanged();
    partial void OnCapKhoChanging(System.Nullable<int> value);
    partial void OnCapKhoChanged();
    partial void OnTinhTrangChanging(System.Nullable<int> value);
    partial void OnTinhTrangChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QuanLyKhoHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKhoHang", DbType="NVarChar(300)")]
		public string DiaChiKhoHang
		{
			get
			{
				return this._DiaChiKhoHang;
			}
			set
			{
				if ((this._DiaChiKhoHang != value))
				{
					this.OnDiaChiKhoHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKhoHang = value;
					this.SendPropertyChanged("DiaChiKhoHang");
					this.OnDiaChiKhoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKho", DbType="NVarChar(200)")]
		public string TenKho
		{
			get
			{
				return this._TenKho;
			}
			set
			{
				if ((this._TenKho != value))
				{
					this.OnTenKhoChanging(value);
					this.SendPropertyChanging();
					this._TenKho = value;
					this.SendPropertyChanged("TenKho");
					this.OnTenKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapKho", DbType="Int")]
		public System.Nullable<int> CapKho
		{
			get
			{
				return this._CapKho;
			}
			set
			{
				if ((this._CapKho != value))
				{
					this.OnCapKhoChanging(value);
					this.SendPropertyChanging();
					this._CapKho = value;
					this.SendPropertyChanged("CapKho");
					this.OnCapKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int")]
		public System.Nullable<int> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyLoHang")]
	public partial class QuanLyLoHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ListIdDonHang;
		
		private System.Nullable<double> _CuocQuaBien;
		
		private System.Nullable<double> _CuocVeKho;
		
		private string _NguoiChuyenBien;
		
		private string _NguoiNhanKho;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnListIdDonHangChanging(string value);
    partial void OnListIdDonHangChanged();
    partial void OnCuocQuaBienChanging(System.Nullable<double> value);
    partial void OnCuocQuaBienChanged();
    partial void OnCuocVeKhoChanging(System.Nullable<double> value);
    partial void OnCuocVeKhoChanged();
    partial void OnNguoiChuyenBienChanging(string value);
    partial void OnNguoiChuyenBienChanged();
    partial void OnNguoiNhanKhoChanging(string value);
    partial void OnNguoiNhanKhoChanged();
    partial void OnThoiGianChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianChanged();
    #endregion
		
		public QuanLyLoHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListIdDonHang", DbType="NVarChar(100)")]
		public string ListIdDonHang
		{
			get
			{
				return this._ListIdDonHang;
			}
			set
			{
				if ((this._ListIdDonHang != value))
				{
					this.OnListIdDonHangChanging(value);
					this.SendPropertyChanging();
					this._ListIdDonHang = value;
					this.SendPropertyChanged("ListIdDonHang");
					this.OnListIdDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocQuaBien", DbType="Float")]
		public System.Nullable<double> CuocQuaBien
		{
			get
			{
				return this._CuocQuaBien;
			}
			set
			{
				if ((this._CuocQuaBien != value))
				{
					this.OnCuocQuaBienChanging(value);
					this.SendPropertyChanging();
					this._CuocQuaBien = value;
					this.SendPropertyChanged("CuocQuaBien");
					this.OnCuocQuaBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocVeKho", DbType="Float")]
		public System.Nullable<double> CuocVeKho
		{
			get
			{
				return this._CuocVeKho;
			}
			set
			{
				if ((this._CuocVeKho != value))
				{
					this.OnCuocVeKhoChanging(value);
					this.SendPropertyChanging();
					this._CuocVeKho = value;
					this.SendPropertyChanged("CuocVeKho");
					this.OnCuocVeKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiChuyenBien", DbType="NVarChar(100)")]
		public string NguoiChuyenBien
		{
			get
			{
				return this._NguoiChuyenBien;
			}
			set
			{
				if ((this._NguoiChuyenBien != value))
				{
					this.OnNguoiChuyenBienChanging(value);
					this.SendPropertyChanging();
					this._NguoiChuyenBien = value;
					this.SendPropertyChanged("NguoiChuyenBien");
					this.OnNguoiChuyenBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhanKho", DbType="NVarChar(100)")]
		public string NguoiNhanKho
		{
			get
			{
				return this._NguoiNhanKho;
			}
			set
			{
				if ((this._NguoiNhanKho != value))
				{
					this.OnNguoiNhanKhoChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhanKho = value;
					this.SendPropertyChanged("NguoiNhanKho");
					this.OnNguoiNhanKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyTaiKhoan")]
	public partial class QuanLyTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _isFacebook;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Phone;
		
		private string _Facebook;
		
		private string _Mail;
		
		private System.Nullable<int> _IdKhoHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnisFacebookChanging(System.Nullable<int> value);
    partial void OnisFacebookChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFacebookChanging(string value);
    partial void OnFacebookChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnIdKhoHangChanging(System.Nullable<int> value);
    partial void OnIdKhoHangChanged();
    #endregion
		
		public QuanLyTaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isFacebook", DbType="Int")]
		public System.Nullable<int> isFacebook
		{
			get
			{
				return this._isFacebook;
			}
			set
			{
				if ((this._isFacebook != value))
				{
					this.OnisFacebookChanging(value);
					this.SendPropertyChanging();
					this._isFacebook = value;
					this.SendPropertyChanged("isFacebook");
					this.OnisFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(200)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(200)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(100)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook", DbType="NVarChar(200)")]
		public string Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this.OnFacebookChanging(value);
					this.SendPropertyChanging();
					this._Facebook = value;
					this.SendPropertyChanged("Facebook");
					this.OnFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NVarChar(100)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhoHang", DbType="Int")]
		public System.Nullable<int> IdKhoHang
		{
			get
			{
				return this._IdKhoHang;
			}
			set
			{
				if ((this._IdKhoHang != value))
				{
					this.OnIdKhoHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhoHang = value;
					this.SendPropertyChanged("IdKhoHang");
					this.OnIdKhoHangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
